### ISSUE TITLE
Revisión POUM + Parcel·lari

### ISSUE THREAD

**Issue by geraldo** [psigcat/web_ctbb#6]
### QGIS (@carlospsig):
- [x] Parcellari: cambiar por Parcel·lari.
- [x] Orden capes: capa “Àmbits de planejament” per encima de “Ordenació”.
- [x] Campos que se han de ver:
  - shape_area: cambiar alias por “Superfície (m2)”
  - nucli: cambiar alias por “Nucli”
  - nucli_parcella: cambiar alias por “Parcel·la”
  - exp: cambiar alias por “Expedient”
  - exp_fitxes: cambiar alias por “Fitxes”

### MapProxy (@geraldo):
- [x] Las etiquetes de la capa “Àmbits de planejament” no se ven bien cuando se cambia de escala.

### Web (@geraldo):
- [x] Falta las opciones de papel:
  - DIN A3 Horitzontal
  - DIN A3 Vertical

### INFORMACIÓ ADICIONAL (documentos)

- [x] Link – Normativa urbanística completa

Hay que substituir o agregar documentos, os dejo el link donde os podeis descargar los correctos:

Carpeta "Memòria":
- [x] Substituir el PDF "INFORMACIÓ": https://www.castellbisbal.cat/media/repository/planejament-urbanistic/2020_poum_documents/02_febrer/00_-_informacio.pdf
- [x] Substituir el PDF "02 – Normes Urbanístiques": https://www.castellbisbal.cat/media/repository/planejament-urbanistic/2020_poum_documents/02_febrer/02_-_normes_urbanistiques.pdf

Carpeta "Modificacions POUM":
- [x] Afegir "Modificació puntual número 8.pdf": https://www.castellbisbal.cat/media/repository/pla-ordenacio-urbanistica/2021/2021_02_14_Modificacio_puntual_numero_8.pdf

Carpeta "Planos"
- [x] Substituir todos os paso enlace de WETRANSFER: https://we.tl/t-7smdrcTZwT

**Comment by carlospsig** [comment]
Ficheros  PDF de la Normativa actualizados y proyectos de QGIS corregidos y subidos.
Proyecto afectado: poum_parcel.qgs
